import numpy as np
import os
import glob

stations = np.genfromtxt('/home/joshua.gebauer/Obs_Simulators/NetworkFiles/profilers.txt')

def namelist_write(lat, lon):
    with open(f'namelist.input', 'w') as f:
        f.write('model                    = 1\n')       # 1-WRF, 2-FastEddy, 3-NCAR LES, 4-MicroHH, 5-CM1’)
        f.write('model_frequency          = 900\n')     # Frequency of model output used for lidar simulation in seconds’)
        f.write('model_dir                = /work2/wof/realtime/nature_run/15-03Z_5min/\n')    # Directory with the model output’)
        f.write('model_timestep           = 0.025\n')   # Model time step (needed for FE output)’)
        f.write('model_prefix             = wrfnr_d01_\n')  # Prefix for the model data filenames’)
        f.write('coordinate_type          = 1\n')      # 1-Lat/lon, 2-x,y,z’)
        f.write('use_calendar             = 1\n')      # If 1 then the start and end times are defined by calendar. If 0 they are in model integration time’)
        f.write('start_year               = 2024\n')   # Ignored if use_calendar is 0’)
        f.write('start_month              = 5\n')     # Ignored if use_calendar is 0’)
        f.write('start_day                = 8\n')     # Ignored if use_calendar is 0’)
        f.write('start_hour               = 18\n')      # Ignored if use_calendar is 0’)
        f.write('start_min                = 0\n')      # Ignored if use_calendar is 0’)
        f.write('start_sec                = 0\n')      # Ignored if use_calendar is 0’)
        f.write('end_year                 = 2024\n')   # Ignored if use_calendar is 0’)
        f.write('end_month                = 5\n')     # Ignored if use_calendar is 0’)
        f.write('end_day                  = 8\n')     # Ignored if use_calendar is 0’)
        f.write('end_hour                 = 20\n')      # Ignored if use_calendar is 0’)
        f.write('end_min                  = 0\n')      # Ignored if use_calendar is 0’)
        f.write('end sec                  = 0\n')      # Ignored if use_calendar is 0’)
        f.write('start_time               = 21000\n')      # Start time of the lidar simulation in seconds (Ignored if use_calendar is 1)’)
        f.write('end_time                 = 21600\n')     # End time of the lidar simulation in seconds (Ignored if use_calendar is 1)’)
        f.write('ncar_les_nscl            = 21\n')     # Number of scalars in NCAR LES run.’)
        f.write('clouds                   = 1\n')      # Extinguish the beam due to clouds’)
        f.write('turb                     = 0\n')      # Add subgrid turbulence’)
        f.write('#\n')
        f.write('# Signal simulation information\n')
        f.write('sim_signal               = 1\n')      # Simulate lidar signal loss based on signal climatology’)
        f.write('signal_climo_file        = /home/joshua.gebauer/Obs_Simulators/LidarSim/Oklahoma_C1.nc\n')
        f.write('points_per_gate          = 20\n')     # Number of lidar samples per range gate’)
        f.write('num_pulses               = 10000\n')   # Number of pulses per gate’)
        f.write('#\n')
        f.write('# Output file information\n')
        f.write('outfile                  = 70deg_VAD_{}_{}.nc\n'.format(lon,lat))
        f.write('append                   = 0\n')      # 1- Append data to existing lidar simulation output file, 0-Create new file’)
        f.write('clobber                  = 0\n')      # 1-Clobber existing file, 0-End simulation if output file exists’)
        f.write('#\n')
        f.write('# Lidar scanning information\n')
        f.write('instantaneous_scan       = 1\n')       # 0-collect data realistically(requires high frequency model output, 1-collect data instantaneously for each scan at each model output time’)
        f.write('number_scans             = 1\n')       # Number of scan files to read in’)
        f.write('scan_file1               = /home/joshua.gebauer/Obs_Simulators/LidarSim/Example_VAD.txt\n')
        f.write('cc1                      = 1\n')       # 1-Means continuously cycle scan 1’)
        f.write('repeat1                  = 0\n')       # The repeat time of scan 1. Ignored if cc1 is 1 or instantaneous_scan is 1.’)
        f.write('dbs1                     = 0\n')       # 1-This is a DBS scan that defines bins by agl’)
        f.write('scan1_az_speed           = -1\n')       # Azimuthal scanning speed for scan 1. 0-Same as motor_az_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('scan1_el_speed           = -1\n')       # Elevation scanning speed for scan 1. 0-Same as motor_el_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('scan_file2               = None\n')
        f.write('cc2                      = 0\n')       # 1-Means continuously cycle scan 2’)
        f.write('repeat2                  = 0\n')     # The repeat time of scan 2. Ignored if cc2 is 1 or instantaneous_scan is 1.’)
        f.write('dbs2                     = 0\n')       # 1-This is a DBS scan that defines bins by agl’)
        f.write('scan2_az_speed           = 0\n')       # Azimuthal scanning speed for scan 2. 0-Same as motor_az_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('scan2_el_speed           = 0\n')       # Elevation scanning speed for scan 2. 0-Same as motor_el_speed, -1-Scan speed - ray_time (psuedo-CSM)’)
        f.write('scan_file3               = None\n')
        f.write('cc3                      = 0\n')       # 1-Means continuously cycle scan 3’)
        f.write('repeat3                  = 0\n')       # The repeat time of scan 3. Ignored if cc3 is 1 or instantaneous_scan is 1.’)
        f.write('dbs3                     = 0\n')       # 1-This is a DBS scan that defines bins by agl’)
        f.write('scan3_az_speed           = 0\n')       # Azimuthal scanning speed for scan 3. 0-Same as motor_az_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('scan3_el_speed           = 0\n')       # Elevation scanning speed for scan 3. 0-Same as motor_el_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('scan_file4               = None\n')
        f.write('cc4                      = 0\n')       # 1-Means continuously cycle scan 4’)
        f.write('repeat4                  = 0\n')       # The repeat time of scan 4. Ignored if cc4 is 1 or instantaneous_scan is 1.’)
        f.write('dbs4                     = 0\n')       # 1-This is a DBS scan that defines bins by agl’)
        f.write('scan4_az_speed           = 0\n')       # Azimuthal scanning speed for scan 4. 0-Same as motor_az_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('scan4_el_speed           = 0\n')       # Elevation scanning speed for scan 4. 0-Same as motor_el_speed, -1-Scan speed = ray_time (psuedo-CSM)’)
        f.write('stare_length             = 0\n')       # Vertical stare length between scheduled scans’)
        f.write('motor_az_speed           = 36\n')     # In degrees/sec (ignored if instantaneous) ’)
        f.write('motor_el_speed           = 36\n')     # In degrees/sec (ignored if instantaneous)’)
        f.write('pulse_width              = 150\n')    # in ns’)
        f.write('gate_width               = 200\n')    # in ns’)
        f.write('maximum_range            = 4\n')      # in km’)
        f.write('dbs_start_height         = 40\n')     # Start height in m AGL for a DBS scan’)
        f.write('dbs_end_height           = 480\n')    # Start height in m AGL for a DBS scan’)
        f.write('dbs_spacing              = 20\n')     # Vertical spacing of DBS points’)
        f.write('sample_resolution        = 5\n')     # This is the resolution in which the model is sampled along the lidar beam ’)
        f.write('nyquist_velocity         = 38.8\n')   # in m/s’)
        f.write('ray_time                 = 0.2083\n')      # Time it takes to collect a ray in seconds’)
        f.write('#\n')
        f.write('#\n')
        f.write('# Lidar position information\n')
        f.write('lidar_lat                = {}\n'.format(lat))   # latitude of simulated lidar in degrees (ignored if coordinate_type is 2)’)
        f.write('lidar_lon                = {}\n'.format(lon))  # longitude of simulated lidar in degrees (ignored if coordinate_type is 2)’)
        f.write('lidar_x                  = -500\n')   # x position of simulated lidar in default units of model (ignored if coordinate_type is 1)’)
        f.write('lidar_y                  = -500\n')   # y position of simulated lidar in default units of model (ignored if coordinate_type is 1)’)
        f.write('lidar_alt                =  -1\n')    # height of the simulated lidar (m above sea level)’)
 
        f.close()

i = 0 
while i < len(stations):
    print(str(i+1) + ': ' + str(stations[i,0]) + ' ' + str(stations[i,1]))
    namelist_write(stations[i,0],stations[i,1])
    matching_files = glob.glob('/work/joshua.gebauer/SimObs/8May2024/obs_nc/lidar/70deg_VAD_' + str(stations[i,0]) +'_' + str(stations[i,1]) + '.nc')
    if len(matching_files) == 0:
        os.system('python LidarSim.py namelist.input --output_dir /work/joshua.gebauer/SimObs/8May2024/obs_nc/lidar/')
    else:
        print('File exists! Skipping')
    i+=1
